platform :ios, '13.0'
prepare_react_native_project!

target 'IntegrationTestApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Nap SSP SDK 의존성 추가
  pod 'AdMixerMediation'
  pod 'AdMixerMediationGAM'
  pod 'AdMixerMediationAdFit'

  target 'IntegrationTestAppTests' do
    inherit! :complete
  end
end
