# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ExampleHostApp' do
  config = use_native_modules!

  # Autolinking adds the base `NapSspPlugin` pod. Mediation adapters are opt-in subspecs - add the
  # ones your ad units actually sell, mirroring napSsp.mediations on Android.
  # https://napmx.github.io/#/ios/native/getting-started
  pod 'NapSspPlugin/GAM'     # Google Ad Manager
  pod 'NapSspPlugin/AdFit'   # Kakao AdFit
  # pod 'NapSspPlugin/Pangle'
  # pod 'NapSspPlugin/AppLovin'
  # pod 'NapSspPlugin/UnityAds'
  # pod 'NapSspPlugin/NAM'   # Naver Ad Manager
  # pod 'NapSspPlugin/Teads' # requires Xcode 26+

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
